# Generated by Django 4.1 on 2023-11-30 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.pessoa')),
                ('consulta_agendada', models.BooleanField(default=False)),
                ('cpf_paciente', models.CharField(max_length=14)),
                ('local', models.CharField(max_length=50)),
                ('mes_consulta', models.IntegerField()),
                ('dia_consulta', models.IntegerField()),
            ],
            bases=('person.pessoa',),
        ),
    ]
