# Generated by Django 4.1 on 2023-11-30 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.pessoa')),
                ('consulta_agendada', models.BooleanField(default=False)),
                ('dados_consulta', models.JSONField(default=dict)),
            ],
            bases=('person.pessoa',),
        ),
    ]
