# Generated by Django 4.1 on 2023-12-08 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='pessoa_ptr',
        ),
        migrations.AddField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(default='Sua Cidade Padrão', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(default='Valor Padrão para CPF', max_length=11),
        ),
        migrations.AddField(
            model_name='paciente',
            name='datanasc',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(default='email@padrao.com', max_length=254),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(default='Valor Padrão para Estado', max_length=255),
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(default='Valor Padrão para Gênero', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome',
            field=models.CharField(default='Valor Padrão para Nome', max_length=255),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(default='Valor Padrão para Telefone', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
